### PR TITLE
Feature/implement testing

### PR DESCRIPTION
**Pull request by johannchopin**
Add some unit tests to cover 90% of the component features.

@romkor Could you init a TravisCI instance for this repo?

### CODE REVIEW

**Comment by johannchopin** [comment]
@romkor Any issue with this testing implementation? 😄

**Comment by romkor** [comment]
@johannchopin have no time for testing yet.

**Comment by johannchopin** [comment]
@romkor No issue I understand 👍 That's why I'm here to help with open-sourced project 😉 I could take care of this part if you want. I already have some cool experience with open-source project like [Gitmoji](https://github.com/carloscuesta/gitmoji). Could I help you more by being a Collaborator?

**Comment by romkor** [comment]
Thanks for your contribution, but currently there are no need for extra Collaborator.

**Comment by johannchopin** [comment]
> have no time for testing yet.

XD well I can easily find the need. Having a single Maintainer is rarely a good scenario for a open-sourced project 😄 Why not trust other peoples? 🤔

**Comment by romkor** [comment]
Hi @johannchopin! Can you resolve conflicts with latest master.

**Comment by johannchopin** [comment]
Hey @romkor 👋sure I will do it asap 👍

**Comment by johannchopin** [comment]
@romkor Done ✅

**Comment by romkor** [comment]
Good job @johannchopin!

**Pull request merged**
