### PR TITLE
♻️ Use vanilla js to export svelte component

### PR DESCRIPTION
**Pull request by johannchopin**
I come into an issue with this library when I tried to test my app using jest. Jest by default ignore `node_module`, so babel will not parse the following which is using es6:

```javascript
import Portal from "./Portal.svelte";

export default Portal;
```

So jest can't understand this lines of code so it ends with errors. We can easily fix that by using a vanilla js export:

```javascript
module.exports = require('./Portal.svelte');
```

I run my tests again and it and was working fine after this modification 👍

### CODE REVIEW

**Comment by romkor** [comment]
`module.exports` is for nodejs. Not sure we should change this.

**Comment by johannchopin** [comment]
Yes but where else would you use a svelte component if it's not a nodejs environment?

**Comment by romkor** [comment]
Nodejs is only compilation environment, target is browser, that's why I think it's more natural to use import/export.
Anyway, we can support both approaches using `module` property in package.json:
```json
{
  ...
  "main": "./src/main.cjs.js",
  "module": "./src/main.es.js",
  ...
}
```

**Comment by romkor** [comment]
Please check this commit https://github.com/romkor/svelte-portal/pull/25/commits/e92c9001622b1d0c7a17f904cb50d43772fee898

**Comment by johannchopin** [comment]
Yes that's perfect thanks 👍

**Pull request merged**
